version: '3.9'
services:
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker-volumes/db:/data/db
  mysql:
    container_name: mysql_container
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: wisdomhub
      MYSQL_DATABASE: wisdomhub_auth
      MYSQL_ROOT_PASSWORD: local
      MYSQL_PASSWORD: local
    ports:
      - 3306:3306
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: wisdomhub
      POSTGRES_DB: wisdomhub_reviews
      POSTGRES_PASSWORD: local
    ports:
      - 5432:5432
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=wisdomhub
      - RABBITMQ_DEFAULT_PASS=wisdomhubpass
    ports:
      # AMQP protocol port
      - 5672:5672
      # Management UI interface port
      - 15672:15672
    volumes:
      - ./docker-volumes/rabbitmq:/var/lib/rabbitmq
    networks:
      - elastic

  elasticsearch:
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    restart: always
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      network.host: 0.0.0.0
      transport.host: 127.0.0.1
      http.host: 0.0.0.0
      xpack.security.enabled: 'true'
      xpack.security.authc.api_key.enabled: 'true'
      xpack.monitoring.collection.enabled: 'true'
      xpack.security.enrollment.enabled: 'true'
      xpack.security.authc.token.enabled: 'true'
      ELASTIC_PASSWORD: admin1234
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./docker-volumes/elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    container_name: kibana_container
    image: docker.elastic.co/kibana/kibana:8.11.1
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana
      - ELASTICSEARCH_SERVICEACCOUNT_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL3dpc2RvbWh1Yi1raWJhbmE6ZG9mc1EzcXpRQTJjanpuSkxnaDgyQQ
      - XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml/:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
    networks:
      - elastic

  notifications:
    container_name: notification_container
    build:
      context: ../server/2-notification-service
      dockerfile: Dockerfile.dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: always
    ports:
      - 4001:4001
    env_file: ../server/2-notification-service/.env
    environment:
      - ENABLE_APM=0
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://wisdomhub:wisdomhubpass@rabbitmq_container:5672
      - SENDER_EMAIL=clarabelle52@ethereal.email
      - SENDER_EMAIL_PASSWORD=nGFBcWrBm8qXyh1sgZ
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - rabbitmq
    networks:
      - elastic

  auth:
    container_name: auth_container
    build:
      context: ../server/3-auth-service
      dockerfile: Dockerfile.dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: always
    ports:
      - 4002:4002
    env_file:
      - ../server/3-auth-service/.env
      - .env.cloudinary
    environment:
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=e73f1ece5087b8a5ae33998952202202
      - JWT_TOKEN=f649f4bd58bcba407446b5d0d75e0e1c
      - NODE_ENV=development
      - API_GATEWAY_URL=http://gateway_container:4000
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://wisdomhub:wisdomhubpass@rabbitmq_container:5672
      - MYSQL_DB=mysql://wisdomhub:local@mysql_container:3306/wisdomhub_auth
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - rabbitmq
      - mysql
    networks:
      - elastic

  users:
    container_name: users_container
    build:
      context: ../server/4-users-service
      dockerfile: Dockerfile.dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: always
    ports:
      - 4003:4003
    env_file:
      - ../server/4-users-service/.env
      - .env.cloudinary
    environment:
      - ENABLE_APM=0
      - DATABASE_URL=mongodb://mongodb_container:27017/wisdomhub-users
      - GATEWAY_JWT_TOKEN=e73f1ece5087b8a5ae33998952202202
      - JWT_TOKEN=f649f4bd58bcba407446b5d0d75e0e1c
      - NODE_ENV=development
      - API_GATEWAY_URL=http:/gateway_container:4000
      - RABBITMQ_ENDPOINT=amqp://wisdomhub:wisdomhubpass@rabbitmq_container:5672
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb
    networks:
      - elastic

  gigs:
    container_name: gigs_container
    build:
      context: ../server/5-gig-service
      dockerfile: Dockerfile.dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: always
    ports:
      - 4004:4004
    env_file:
      - ../server/5-gig-service/.env
      - .env.cloudinary
    environment:
      - ENABLE_APM=0
      - DATABASE_URL=mongodb://mongodb_container:27017/wisdomhub-gig
      - GATEWAY_JWT_TOKEN=e73f1ece5087b8a5ae33998952202202
      - JWT_TOKEN=f649f4bd58bcba407446b5d0d75e0e1c
      - NODE_ENV=development
      - API_GATEWAY_URL=http:/gateway_container:4000
      - RABBITMQ_ENDPOINT=amqp://wisdomhub:wisdomhubpass@rabbitmq_container:5672
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb
    networks:
      - elastic
  
  gateway:
    container_name: gateway_container
    build:
      context: ../server/1-gateway-service
      dockerfile: Dockerfile.dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    restart: always
    ports:
      - 4000:4000
    env_file: ../server/1-gateway-service/.env
    environment:
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=e73f1ece5087b8a5ae33998952202202
      - JWT_TOKEN=f649f4bd58bcba407446b5d0d75e0e1c
      - NODE_ENV=development
      - SECRET_KEY_ONE=a6f835373166715f35344776108c6e47
      - SECRET_KEY_TWO=6cd35fd7ece398ff858d0d5bce17ad03
      - CLIENT_URL=http://localhost:4002
      - AUTH_BASE_URL=http://localhost:4002
      - USERS_BASE_URL=http://localhost:4003
      - GIG_BASE_URL=http://localhost:4004
      - MESSAGE_BASE_URL=http://localhost:4005
      - ORDER_BASE_URL=http://localhost:4006
      - REVIEW_BASE_URL=http://localhost:4007
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic:
    name: elastic