FROM node:21-alpine3.18

WORKDIR /app

COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src

RUN ls -la
RUN rm -f .npmrc
ARG NPM_TOKEN
ENV NPM_TOKEN=${NPM_TOKEN}
RUN echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" > .npmrc && \
    echo "@hassonor:registry=https://npm.pkg.github.com/" >> .npmrc
RUN npm install && npm install -g cross-env nodemon

EXPOSE 4002

cmd ["npm","run","dev"]
