name: Publish
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build
      - run: |
          echo @hassonor:https://npm.pkg.github.com/ > ./server/9-wisdomhub-shared/build/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> ./server/9-wisdomhub-shared/build/.npmrc
      - run: npm publish
        working-directory: ./server/9-wisdomhub-shared/build/
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
